---
# - name: replace ifcfg file
#   ansible.builtin.template: 
#     src: templates/ifcfg.j2
#     dest: /etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}
# 
# - name: restart networking 
#   ansible.builtin.systemd:
#     state: restarted
#     name: network

- name: set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: systemd
