---
- hosts: all
  roles:
#    - yum_update
#    - inject_ssh_key
#    - network_config

- hosts: kube_nodes
  roles:
#    - install_docker
#    - install_k8s_prereqs
    - install_k8s_prereqs

- hosts: master1
  roles:
#    - install_docker
